### PR TITLE
fix(replicator): GET catalog contents from ns only when necessary

### PR DESCRIPTION
**Pull request by peterthomassen**
When there are many zones configured, fetching the catalog zone from GET zones/catalog.internal. on ns is very significant, as all records are serialized and transmitted. This commit introduces a precheck via DNS SOA query, and runs the GET request only when the serial has changed.

Tested on sandbox; significant load reduction even there.

### CODE REVIEW

**Comment by peterthomassen** [comment]
For reference, here's the impact on CPU load (as measured on dens1sin, which currently receives production replication (but no public queries). The drop is roughly a factor of 4.

**Comment by nils-wisiol** [comment]
I'm wondering what happens if the catalog AXFR gets lost. Regardless of we apply this PR, the serial wouldn't increase and changes would stall, correct?

**Review by nils-wisiol — DISMISSED** [review]

**Comment by nils-wisiol** [comment]
I fixed the `__init__` method, which is not supposed to return something. Please review and squash

**Review by nils-wisiol — APPROVED** [review]

**Comment by peterthomassen** [comment]
> I'm wondering what happens if the catalog AXFR gets lost. Regardless of we apply this PR, the serial wouldn't increase and changes would stall, correct?

Yes, but it should(tm) not get lost as it is TCP. - Also, the catalog is only responsible for domain additions/deletions, not for regular DNS updates.

**Pull request merged**
